### ISSUE TITLE
docker-compose up: "issue with node-fibers" fibers.node is missing. 

### ISSUE THREAD

**Issue by BitSledge** [ryhanson/lair-docker#20]
docker version 19.03.6

$ git clone https://github.com/ryhanson/lair-docker.git
$ cd lair-docker
$ docker-compose build
$ docker-compose up
lair_lair  |
lair_lair  | > meteor-dev-bundle@0.0.0 start /root/app/bundle/programs/server
lair_lair  | > node /root/app/bundle/main.js
lair_lair  |
lair_lair  | ## There is an issue with `node-fibers` ##
lair_lair  | `/root/app/bundle/programs/server/node_modules/fibers/bin/linux-x64-72/fibers.node` is missing.
lair_lair  |
lair_lair  | Try running this to fix the issue: /root/.meteor/packages/meteor-tool/.1.9.2.7xwsrp.rm4gc++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /root/app/bundle/programs/server/node_modules/fibers/build
lair_lair  | /root/app/bundle/programs/server/node_modules/fibers/fibers.js:20
lair_lair  | throw new Error('Missing binary. See message above.');
lair_lair  | ^
lair_lair  |
lair_lair  | Error: Missing binary. See message above.
lair_lair  |     at Object.<anonymous> (/root/app/bundle/programs/server/node_modules/fibers/fibers.js:20:8)
lair_lair  |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
lair_lair  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
lair_lair  |     at Module.load (internal/modules/cjs/loader.js:1002:32)
lair_lair  |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
lair_lair  |     at Module.require (internal/modules/cjs/loader.js:1044:19)
lair_lair  |     at require (internal/modules/cjs/helpers.js:77:18)
lair_lair  |     at Object.<anonymous> (/root/app/bundle/programs/server/boot.js:1:13)
lair_lair  |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
lair_lair  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
lair_lair  | npm ERR! code ELIFECYCLE
lair_lair  | npm ERR! errno 1
lair_lair  | npm ERR! meteor-dev-bundle@0.0.0 start: `node /root/app/bundle/main.js`
lair_lair  | npm ERR! Exit status 1
lair_lair  | npm ERR!
lair_lair  | npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script.
lair_lair  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lair_lair  |
lair_lair  | npm ERR! A complete log of this run can be found in:
lair_lair  | npm ERR!     /root/.npm/_logs/2020-02-26T22_26_16_216Z-debug.log
lair_lair exited with code 1

**Comment by gmassawe** [comment]
im having the same issue
